### ISSUE TITLE
Pinned mentions that are over multiple lines long overlap

### ISSUE THREAD

**Issue by RadiantSol** [vyneer/dgg-chat-gui-scripts#24]
Whenever there are multiple mentions pinned that take up more than one line, the messages overlap and partially merge.

Steps to reproduce:
Step 1. Turn on pinned mention messages feature

Step 2. Say something dumb in chat

Step 3. Look at top of chat

![screenshot of issue](https://user-images.githubusercontent.com/80371359/167691285-dc787d2f-3b1d-4e4e-b4a1-878cec6d180e.png)

**Comment by vyneer** [comment]
This is just kind of how it works, unfortunately. It's probably possible to rewrite it to be "prettier", but it would make it have a non-insignificant impact on performance and I'd like to avoid that.

I think a good solution would be to make every other mention have a slightly different/darker shade of blue, so that the overlap isn't as jarring/confusing.

**Comment by vyneer** [comment]
Sorta fixed in #30? Couldn't do every other mention, so i added a small border on the bottom of each, not perfect, of course, but better than before.
